(ns translations.fpoc-French.po (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
 translations
 {"|Log out" "Connectez - Out",
  "|Please supply your name.`" "Veuillez fournir votre nom.",
  "|Glad you could join us!"
  "Content que vous puissiez vous rejoindre!",
  "|Password" "Mot de passe",
  "|Pay Someone page" "Pay Someone page",
  "|Pay Someone" "Payer quelqu'un",
  "|Account Limits page" "Page Limites de compte",
  "|Password must be at least 7 characters long"
  "Le mot de passe doit comporter au moins 7 caractères",
  "|Account Number" "Numéro de compte",
  "|Welcome!" "Bienvenue!",
  "|International" "International",
  "|Profile" "Profil",
  "|Account to Account Transfer" "Compte pour le transfert de compte",
  "|Account" "Compte",
  "|"
  "MIME-Version: 1.0\\nContent-Type: text/plain; charset=UTF-8\\nContent-Transfer-Encoding: 8bit\\nX-Generator: POEditor.com\\nProject-Id-Version: fpoc\\nLanguage: fr\\n",
  "|Email Address" "Adresse e-mail",
  "|Thanks!" "Merci!",
  "|Passwords must match" "les mots de passe doivent correspondre",
  "|Sign in" "se connecter",
  "|Please, log in." "Veuillez vous connecter.",
  "|Welcome! Your account has been created. "
  "Bienvenue! Votre compte a été créé.",
  "|Email" "Email",
  "|Must be a valid email address.`"
  "Doit être une adresse e-mail valide.",
  "|Unable to contact server. Try again later."
  "Impossible de contacter le serveur. Réessayez plus tard.",
  "|Don't have a login yet? " "Vous n'êtes pas encore connecté?",
  "|A server error happened. Please try again."
  "Une erreur de serveur s'est produite. Veuillez réessayer.",
  "|Bad username or password."
  "Nom d'utilisateur ou mot de passe incorrect.",
  "|Sign Up!" "S'inscrire!",
  "|Local" "Local",
  "|Main page" "Page d'accueil",
  "|Send Money Abroad" "Envoyer de l'argent à l'étranger",
  "|Profile page" "Page de profil",
  "|Sign up!" "S'inscrire!",
  "|Preferences page" "Page Préférences",
  "|Name" "prénom",
  "|Verify Password" "vérifier le mot de passe",
  "|Balance" "Équilibre",
  "|Account Limits" "Limites de compte"})

(swap!
 fulcro.i18n/*loaded-translations*
 assoc
 "fpoc-French.po"
 translations)