(ns translations.fpoc-Maori.po (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
 translations
 {"|Log out" "Puta atu",
  "|Please supply your name.`" "Tukuna koa to ingoa \\\"",
  "|Glad you could join us!" "Kia pai koe ki te uru atu ki a matou!",
  "|Password" "Kupuhipa",
  "|Pay Someone page" "Tuku tetahi whārangi",
  "|Pay Someone" "Utu tetahi",
  "|Account Limits page" "Tautuhinga Tautuhinga Moni",
  "|Password must be at least 7 characters long"
  "Me roa rawa te roa o te kupuhipa",
  "|Account Number" "Tau nama",
  "|Welcome!" "Nau mai!",
  "|International" "International",
  "|Profile" "Profile",
  "|Account to Account Transfer" "Pūkete ki te Whakawhiti Pūkete",
  "|Account" "Pūkete",
  "|"
  "MIME-Version: 1.0\\nContent-Type: text/plain; charset=UTF-8\\nContent-Transfer-Encoding: 8bit\\nX-Generator: POEditor.com\\nProject-Id-Version: fpoc\\nLanguage: mi\\n",
  "|Email Address" "Wāhitau Īmēra",
  "|Thanks!" "Mauruuru!",
  "|Passwords must match" "Me tika nga kupuhipa",
  "|Sign in" "Waitohu",
  "|Please, log in." "Tena, takiuru.",
  "|Welcome! Your account has been created. "
  "Nau mai! I hangahia to korero.",
  "|Email" "Īmēra",
  "|Must be a valid email address.`"
  "Me waiho he wāhitau īmēra tika. \\\"",
  "|Unable to contact server. Try again later."
  "Kāore e taea te whakapā atu ki te tūmau. Ngana ano i muri.",
  "|Don't have a login yet? " "Karekau he takiuru ano?",
  "|A server error happened. Please try again."
  "I puta he hapa tūmau. Tena ngana ano.",
  "|Bad username or password." "Ingoa ingoa kino, kupuhipa ranei.",
  "|Sign Up!" "Waitohu Up!",
  "|Local" "Paetata",
  "|Main page" "Whārangi matua",
  "|Send Money Abroad" "Tukuna Moni Hape",
  "|Profile page" "Whārangi tohu",
  "|Sign up!" "Waitohu!",
  "|Preferences page" "Nga whārangi manakohanga",
  "|Name" "Ingoa",
  "|Verify Password" "Manatoko Kupuhipa",
  "|Balance" "Tuhinga",
  "|Account Limits" "Tautuhinga Pūkete"})

(swap!
 fulcro.i18n/*loaded-translations*
 assoc
 "fpoc-Maori.po"
 translations)