(ns translations.fr (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
 translations
 {"|Log out" "Log out",
  "|Please supply your name.`" "Please supply your name.`",
  "|Glad you could join us!" "Glad you could join us!",
  "|Password" "Password",
  "|Pay Someone page" "Pay Someone page",
  "|Pay Someone" "Pay Someone",
  "|Account Limits page" "Account Limits page",
  "|Password must be at least 7 characters long"
  "Password must be at least 7 characters long",
  "|Account Number" "Account Number",
  "|Welcome!" "Welcome!",
  "|International" "International",
  "|Profile" "Profile",
  "|Account to Account Transfer" "Account to Account Transfer",
  "|Account" "Account",
  "|Email Address" "Email Address",
  "|Thanks!" "Thanks!",
  "|Passwords must match" "Passwords must match",
  "|Sign in" "Sign in",
  "|Please, log in." "Please, log in.",
  "|Welcome! Your account has been created. "
  "Welcome! Your account has been created. ",
  "|Email" "Email",
  "|Must be a valid email address.`" "Must be a valid email address.`",
  "|Unable to contact server. Try again later."
  "Unable to contact server. Try again later.",
  "|Don't have a login yet? " "Don't have a login yet? ",
  "|A server error happened. Please try again."
  "A server error happened. Please try again.",
  "|Bad username or password." "Bad username or password.",
  "|Sign Up!" "Sign Up!",
  "|Local" "Local",
  "|Main page" "Main page",
  "|Send Money Abroad" "Send Money Abroad",
  "|Profile page" "Profile page",
  "|Sign up!" "Sign up!",
  "|Preferences page" "Preferences page",
  "|Name" "Name",
  "|Verify Password" "Verify Password",
  "|Balance" "Balance",
  "|Account Limits" "Account Limits"})

(swap! fulcro.i18n/*loaded-translations* assoc "fr" translations)